name: enclove
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_nearby_connections:
    path: ./packages/flutter_nearby_connections
  flutter_styled_toast: ^2.2.1
  permission_handler: ^10.2.0
  device_info: ^2.0.3
  sqlite_crdt: ^3.0.2
  path_provider: ^2.0.8
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
